[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "netlify"
  NODE_VERSION = "22"
  BUN_VERSION = "1.2.22"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"